version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "biblioteca"
    ports:
      - "3306:3306"
    volumes:
      - biblioteca_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: biblioteca_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  biblioteca_data:
